[package]
name = "day17_clumsy_crucible"
version = "0.1.0"
edition = "2021"

[dependencies]
array2d = "0.3.2"

[lints.rust]
unused = "allow"
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"

[workspace]

members = [
    "src/list.rs",
    "src/map.rs",
    "src/main.rs"
]
